name: Run JobPing every 6 hours

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:       # Allow manual runs from GitHub UI

jobs:
  run-jobping:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v3

      - name: 🧰 Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: 📦 Restore dependencies
        run: dotnet restore

      - name: 🚀 Run JobPing
        run: dotnet run --project JobPing.App
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          JOB_SITE_URLS: ${{ secrets.JOB_SITE_URLS }}

      - name: 💾 Commit updated jobs.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add jobs.json
          git commit -m "Update jobs.json [skip ci]" || echo "No changes to commit"
          git push
